// Google AI Overview Remover Content Script - Debug Version
(function() {
    'use strict';
    
    console.log('Google AI Overview Remover: Debug version loaded');
    
    // Function to check if element contains AI Overview content
    function isAIOverview(element) {
        const text = element.textContent.toLowerCase();
        const html = element.innerHTML.toLowerCase();
        
        // Check for AI-related text patterns
        const aiPatterns = [
            'ai overview',
            'ai-generated',
            'generated by ai',
            'ai summary',
            'ai answer',
            'ai response',
            'ai explanation',
            'ai insight',
            'ai analysis',
            'ai-generated summary',
            'ai-generated answer',
            'ai-generated response',
            'ai-generated explanation',
            'ai-generated insight',
            'ai-generated analysis',
            'overview generated by ai',
            'summary generated by ai',
            'answer generated by ai',
            'response generated by ai',
            'explanation generated by ai',
            'insight generated by ai',
            'analysis generated by ai'
        ];
        
        // Check for AI-related attributes
        const hasAIAttributes = element.hasAttribute('data-ai') ||
                               element.getAttribute('data-ved')?.includes('ai') ||
                               element.getAttribute('jscontroller')?.includes('ai') ||
                               element.getAttribute('class')?.includes('ai') ||
                               element.getAttribute('id')?.includes('ai');
        
        // Check for AI-related text content
        const hasAIText = aiPatterns.some(pattern => text.includes(pattern) || html.includes(pattern));
        
        // Check for specific AI Overview indicators
        const hasAIIndicators = element.querySelector('[data-ai]') ||
                               element.querySelector('[data-ved*="ai"]') ||
                               element.querySelector('[jscontroller*="ai"]') ||
                               element.querySelector('.ai-overview') ||
                               element.querySelector('#ai-overview') ||
                               element.querySelector('[class*="ai"]') ||
                               element.querySelector('[id*="ai"]');
        
        const isAI = hasAIAttributes || hasAIText || hasAIIndicators;
        
        if (isAI) {
            console.log('Found potential AI Overview element:', {
                element: element,
                tagName: element.tagName,
                className: element.className,
                id: element.id,
                textContent: element.textContent.substring(0, 100) + '...',
                hasAIAttributes: hasAIAttributes,
                hasAIText: hasAIText,
                hasAIIndicators: hasAIIndicators
            });
        }
        
        return isAI;
    }
    
    // Function to remove AI Overview elements
    function removeAIOverview() {
        let removedCount = 0;
        
        console.log('Google AI Overview Remover: Starting removal process');
        
        // Method 1: Look for elements with AI-related attributes
        const attributeSelectors = [
            '[data-ai]',
            '[data-ved*="ai"]',
            '[jscontroller*="ai"]',
            '[class*="ai"]',
            '[id*="ai"]',
            '.ai-overview',
            '#ai-overview',
            '[data-ai-overview]',
            '[data-ai-summary]',
            '[data-ai-answer]',
            '[data-ai-response]',
            '[data-ai-explanation]',
            '[data-ai-insight]',
            '[data-ai-analysis]'
        ];
        
        console.log('Checking attribute selectors...');
        attributeSelectors.forEach(selector => {
            try {
                const elements = document.querySelectorAll(selector);
                console.log(`Selector "${selector}" found ${elements.length} elements`);
                elements.forEach(element => {
                    if (isAIOverview(element)) {
                        console.log('Removing element with selector:', selector);
                        element.remove();
                        removedCount++;
                    }
                });
            } catch (e) {
                console.log(`Error with selector "${selector}":`, e);
            }
        });
        
        // Method 2: Look for search result containers that might contain AI Overview
        console.log('Checking search result containers...');
        const searchResults = document.querySelectorAll('.g, .tF2Cxc, .MjjYud, .g-blk, .g-blk .g');
        console.log(`Found ${searchResults.length} search result containers`);
        searchResults.forEach(result => {
            if (isAIOverview(result)) {
                console.log('Removing search result container');
                result.remove();
                removedCount++;
            }
        });
        
        // Method 3: Look for elements with AI-related text content
        console.log('Checking all elements for AI content...');
        const allElements = document.querySelectorAll('div, section, article, main');
        console.log(`Found ${allElements.length} elements to check`);
        allElements.forEach(element => {
            if (isAIOverview(element)) {
                // Try to find the parent search result container
                const parentResult = element.closest('.g, .tF2Cxc, .MjjYud, .g-blk');
                if (parentResult) {
                    console.log('Removing parent search result container');
                    parentResult.remove();
                    removedCount++;
                } else {
                    console.log('Removing element directly');
                    element.remove();
                    removedCount++;
                }
            }
        });
        
        // Method 4: Look for specific AI Overview containers
        console.log('Checking AI containers...');
        const aiContainers = document.querySelectorAll('[data-ved], [jscontroller]');
        console.log(`Found ${aiContainers.length} AI containers`);
        aiContainers.forEach(container => {
            if (isAIOverview(container)) {
                console.log('Removing AI container');
                container.remove();
                removedCount++;
            }
        });
        
        // Method 5: Look for elements that might be AI Overview based on position and content
        console.log('Checking potential AI elements...');
        const potentialAIElements = document.querySelectorAll('div[data-ved], div[jscontroller]');
        console.log(`Found ${potentialAIElements.length} potential AI elements`);
        potentialAIElements.forEach(element => {
            if (isAIOverview(element) && element.offsetHeight > 50) {
                console.log('Removing potential AI element');
                element.remove();
                removedCount++;
            }
        });
        
        if (removedCount > 0) {
            console.log(`Google AI Overview Remover: Removed ${removedCount} AI Overview elements`);
        } else {
            console.log('Google AI Overview Remover: No AI Overview elements found');
        }
    }
    
    // Function to remove AI Overview with more aggressive detection
    function aggressiveRemoveAIOverview() {
        let removedCount = 0;
        
        console.log('Google AI Overview Remover: Starting aggressive removal');
        
        // Look for any element that might be AI Overview
        const allElements = document.querySelectorAll('*');
        console.log(`Checking ${allElements.length} elements aggressively`);
        allElements.forEach(element => {
            if (isAIOverview(element)) {
                // Try to remove the entire search result container
                const searchResult = element.closest('.g, .tF2Cxc, .MjjYud, .g-blk');
                if (searchResult) {
                    console.log('Aggressively removing search result container');
                    searchResult.remove();
                    removedCount++;
                } else {
                    console.log('Aggressively removing element');
                    element.remove();
                    removedCount++;
                }
            }
        });
        
        if (removedCount > 0) {
            console.log(`Google AI Overview Remover (Aggressive): Removed ${removedCount} AI Overview elements`);
        } else {
            console.log('Google AI Overview Remover (Aggressive): No AI Overview elements found');
        }
    }
    
    // Run immediately
    console.log('Google AI Overview Remover: Running initial removal');
    removeAIOverview();
    
    // Set up observer for dynamic content
    const observer = new MutationObserver((mutations) => {
        let shouldCheck = false;
        mutations.forEach((mutation) => {
            if (mutation.type === 'childList' && mutation.addedNodes.length > 0) {
                shouldCheck = true;
            }
        });
        
        if (shouldCheck) {
            console.log('Google AI Overview Remover: DOM changed, checking for AI Overview');
            setTimeout(removeAIOverview, 100);
            setTimeout(aggressiveRemoveAIOverview, 500);
        }
    });
    
    // Start observing
    observer.observe(document.body, {
        childList: true,
        subtree: true
    });
    
    // Also run on page load events
    window.addEventListener('load', () => {
        console.log('Google AI Overview Remover: Page loaded, checking for AI Overview');
        setTimeout(removeAIOverview, 500);
        setTimeout(aggressiveRemoveAIOverview, 1000);
    });
    window.addEventListener('popstate', () => {
        console.log('Google AI Overview Remover: Page state changed, checking for AI Overview');
        setTimeout(removeAIOverview, 100);
        setTimeout(aggressiveRemoveAIOverview, 500);
    });
    
    // Run periodically to catch any missed elements
    setInterval(() => {
        console.log('Google AI Overview Remover: Periodic check');
        removeAIOverview();
    }, 2000);
    
    console.log('Google AI Overview Remover: Debug version initialized');
    
})();
